### ISSUE TITLE
ccloud.get_kafka_topic_output seems to always raise error 'Invalid address to set: []string{"http_endpoint"}'

### ISSUE THREAD

**Issue by ebertn** [pulumi/pulumi-confluentcloud#181] opened 2023-08-15 00:49 UTC
### What happened?

Trying to fetch a topic using the following python:
```
ccloud.get_kafka_topic_output(
    credentials=GetKafkaTopicCredentialsArgs(
        key="<My key>",
        secret="<My secret>",
    ),
    kafka_cluster=GetKafkaTopicKafkaClusterArgs(
        id="<My cluster ID>",
    ),
    rest_endpoint="<My REST endpoint>",
    topic_name="<My topic>",
)
```

I get the following exception:
```
error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 197, in <module>
        loop.run_until_complete(coro)
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
        return future.result()
      File "/tests/topic_bug/.venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 137, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/topic_bug/.venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await wait_for_rpcs()
      File "/topic_bug/.venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 121, in wait_for_rpcs
        raise exception
      File "/topic_bug/.venv/lib/python3.9/site-packages/pulumi/output.py", line 199, in run
        transformed: Input[U] = func(value)
      File "/topic_bug/.venv/lib/python3.9/site-packages/pulumi_confluentcloud/_utilities.py", line 243, in <lambda>
        }).apply(lambda resolved_args: func(*resolved_args['args'],
      File "/topic_bug/.venv/lib/python3.9/site-packages/pulumi_confluentcloud/get_kafka_topic.py", line 126, in get_kafka_topic
        __ret__ = pulumi.runtime.invoke('confluentcloud:index/getKafkaTopic:getKafkaTopic', __args__, opts=opts, typ=GetKafkaTopicResult).value
      File "/topic_bug/.venv/lib/python3.9/site-packages/pulumi/runtime/invoke.py", line 147, in invoke
        raise invoke_error
    Exception: invoke of confluentcloud:index/getKafkaTopic:getKafkaTopic failed: invocation of confluentcloud:index/getKafkaTopic:getKafkaTopic returned an error: invoking confluentcloud:index/getKafkaTopic:getKafkaTopic: 1 error occurred:
        * error reading Kafka Topic "<My topic name>": Invalid address to set: []string{"http_endpoint"}
```

### Expected Behavior

Successfully return information about the topic without throwing an exception

### Steps to reproduce

1. Create a python file called `__main__.py` with the following contents:
```
import pulumi_confluentcloud as ccloud
from pulumi_confluentcloud import GetKafkaTopicCredentialsArgs, \
    GetKafkaTopicKafkaClusterArgs

res = ccloud.get_kafka_topic_output(
    credentials=GetKafkaTopicCredentialsArgs(
        key="<My key>",
        secret="<My secret>",
    ),
    kafka_cluster=GetKafkaTopicKafkaClusterArgs(
        id="<My cluster ID>",
    ),
    rest_endpoint="<My REST endpoint>",
    topic_name="<My topic>",
)
```

2. Fill in the above fields (as strings) with your cluster and topic details

3. Create another file called `Pulumi.yaml` with this contents:
```
name: test
runtime:
  name: python
  options:
    virtualenv: .venv
description: A test
```

4. Run these commands:
```
# Install dependencies
python3 -m venv .venv
source .venv/bin/activate
pip install pulumi
pip install pulumi-confluentcloud

# Run pulumi script
pulumi up
```

### Output of `pulumi about`

CLI          
Version      3.74.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME            VERSION
confluentcloud  1.24.0
python          unknown

Host     
OS       darwin
Version  13.4.1
Arch     x86_64

This project is written in python: executable='/topic_bug/.venv/bin/python3' version='3.9.0
'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/nicholas-ebert
User           nicholas-ebert
Organizations  nicholas-ebert, daimler-mic

Dependencies:
NAME                   VERSION
pip                    23.2.1
pulumi-confluentcloud  1.24.0
setuptools             68.0.0
wheel                  0.41.1

Pulumi locates its logs in /var/folders/zc/xwj0l22j6q13ddpft5dmbsm9xlqk42/T/ by default

### Additional context

This seems to happen regardless of if I use strings or Outputs for the fields. Also this doesn't happen if I use `await get_kafka_topic()`, but this isn't a great pattern for my use case.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment] 2023-08-16 00:49
Hello @ebertn,

We appreciate you bringing this issue to our attention, and we apologize for any inconvenience you're experiencing. After a thorough investigation, we have identified the root cause of the problem you're facing.

The issue appears to be related to a patch applied to the upstream provider. This patch is designed to handle the deprecated `http_endpoint` field, which has now been renamed to `rest_endpoint`. However, there seems to be an issue with how this patch interacts with the schema for the datasource. Specifically, the datasource schema doesn't include the `rest_endpoint` field, only the resource schema does.

To address this, we will work on updating our patch to account for this discrepancy and ensure that the necessary fields are correctly handled. This should help resolve the issue you've encountered.

We appreciate your understanding and patience as we work on resolving this matter. If you have any further questions or concerns, please don't hesitate to reach out. Your feedback is valuable to us as we strive to improve our services.

**Comment by ebertn** [comment] 2023-08-17 17:06
Hey @rquitales, thanks for the quick response! No problem, we're patiently awaiting this feature :D

**Closed** 2023-08-25 18:32 UTC
Labels: customer/feedback, impact/usability, kind/bug
